# 基礎

In [1]:
import tensorflow as tf

C:\Users\AutoUser\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\AutoUser\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\AutoUser\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\AutoUser\Anaconda3\envs\tensorflow\lib\s

In [3]:
W = tf.Variable(10)
assign_op = W.assign(100)

#在session中啟動計算圖

with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())
    print(sess.run(assign_op))

10
100


In [4]:
W

<tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>

In [5]:
assign_op

<tf.Tensor 'Assign_1:0' shape=() dtype=int32_ref>

In [9]:
# 示例 :變量與操作

tmp_var = tf.Variable(3, name = "tmp_var")

#把自己乘以2的結果賦值給自己

tmp_var_times_two = tmp_var.assign(2* tmp_var)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(tmp_var_times_two))
    print(sess.run(tmp_var_times_two))
    print(sess.run(tmp_var_times_two))

6
12
24


In [13]:
#session與變量

W = tf.Variable(15)
sess1 = tf.Session()
sess2 = tf.Session()


sess1.run(W.initializer)
sess2.run(W.initializer) #為什麼要 initializer

print(sess1.run(W.assign_add(15)))
print(sess2.run(W.assign_sub(2)))


print(sess1.run(W.assign_add(100)))
print(sess2.run(W.assign_sub(50)))

sess1.close()
sess2.close() #為什麼要close

30
13
130
-37


## 2.op與計算圖

In [16]:
import numpy as np

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)

with tf.Session() as sess:
    #寫入日志芳變tensorboard讀取
    writer = tf.summary.FileWriter('./graphs',sess.graph) #用意是什麼? 方便查看結構運作
    print(sess.run(x))

    writer.close() #記得把writer關閉

5


In [18]:
#示例 : 向量相乘

a = tf.constant([2,2], name = 'a')
b = tf.constant([[1,2],[3,4]],name = 'b')

x = tf.multiply(a,b ,name = 'dot_product')

with tf.Session() as sess:
    print(sess.run(x)) #不是variable不用初始化

[[2 4]
 [6 8]]


In [21]:
#示例: tf.zeros等建構變量

x = tf.zeros([2,3], tf.int32)
y = tf.zeros_like(x, optimize = True) # optimize 的用意?

with tf.Session() as sess:
    print(sess.run(y))
    

[[0 0 0]
 [0 0 0]]


In [25]:
#示例 :linespace 與 range

x = tf.linspace(10.0,13.0,4,name = 'linespace')
y = tf.range(5,name = 'range')

with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))

[10. 11. 12. 13.]
[0 1 2 3 4]


In [27]:
# 示例:zeros_like 與 one_like

sample = tf.multinomial(tf.constant([[1.,3.,1]]),5)

with tf.Session() as sess:
    for _ in range(10):
        print(sess.run(sample))

t_0 = 19 
x = tf.zeros_like(t_0) # ==> 0
y = tf.ones_like(t_0) # ==> 1

with tf.Session() as sess:
    print(sess.run([x, y]))

[[1 1 1 1 1]]
[[1 1 1 0 1]]
[[1 1 1 1 1]]
[[1 1 1 1 1]]
[[0 1 1 2 1]]
[[1 1 0 1 1]]
[[1 1 1 1 0]]
[[1 2 2 1 1]]
[[2 1 1 1 0]]
[[2 1 0 1 1]]
[0, 1]


In [28]:
t_1 = ['apple', 'peach', 'banana']
x = tf.zeros_like(t_1) # ==> ['' '' '']
y = tf.ones_like(t_1) # ==> TypeError: Expected string, got 1 of type 'int' instead.

TypeError: Expected string, got 1 of type 'int' instead.

In [29]:
t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]] 
x = tf.zeros_like(t_2) # ==> 2x2 tensor, all elements are False
y = tf.ones_like(t_2) # ==> 2x2 tensor, all elements are True
with tf.Session() as sess:
    print(sess.run([x, y]))

[array([[False, False, False],
       [False, False, False],
       [False, False, False]]), array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])]


In [30]:
with tf.variable_scope('meh') as scope:
    a = tf.get_variable('a', [10])
    b = tf.get_variable('b', [100])

writer = tf.summary.FileWriter('test', tf.get_default_graph())


x = tf.Variable(2.0)
y = 2.0 * (x ** 3)
z = 3.0 + y ** 2
grad_z = tf.gradients(z, [x, y])
with tf.Session() as sess:
    sess.run(x.initializer)
    print(sess.run(grad_z))

W1128 15:22:13.768020 25156 deprecation.py:506] From C:\Users\AutoUser\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W1128 15:22:13.823984 25156 deprecation.py:323] From C:\Users\AutoUser\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_grad.py:1205: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


[768.0, 32.0]


## feed_dic 與計算圖

In [31]:
# 示例
# 占位符placeholder与feed_dict
a = tf.placeholder(tf.float32, shape=[3]) # float32类型，长度为3的向量

b = tf.constant([5, 5, 5], tf.float32) # float32类型的常量

c = a + b  # 求和，更具体的计算图操作是 tf.add(a, b)

with tf.Session() as sess:
    # 把a传入计算图，在session中完成计算
    print(sess.run(c, {a: [1, 2, 3]}))

[6. 7. 8.]


In [32]:
# 示例
# 中途传入a进行替换
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    replace_dict = {a: 15}
    print(sess.run(b, feed_dict=replace_dict))

45
